const $=id=>document.getElementById(id),video=$("video"),file=$("file"),display=$("display"),empty=$("empty"),ticker=$("ticker"),track=$("track"),text=$("text"),status=$("status"),duration=$("duration"),fileName=$("fileName");
let url="",running=false,anim;
const units=track.querySelectorAll(".ticker-unit"),speeds=[.65,1,1.45];
const fmt=s=>{if(!Number.isFinite(s))return"--:--";s=Math.floor(s);return`${Math.floor(s/60)}:${String(s%60).padStart(2,"0")}`};
const setStatus=m=>status.textContent=m;
const setText=v=>{units.forEach(u=>u.textContent=v?`${v}   •   `:"");track.style.visibility=v?"visible":"hidden"};
const setPos=p=>{ticker.classList.remove("top","mid","bottom");ticker.classList.add(p)};
anim=track.animate([{transform:"translate3d(0,0,0)"},{transform:"translate3d(-50%,0,0)"}],{duration:10000,iterations:Infinity,easing:"linear"});anim.pause();
file.addEventListener("change",()=>{const f=file.files[0];if(!f)return;if(!f.type.startsWith("video/")){setStatus("Please choose a video file.");file.value="";return}if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(f);video.src=url;video.load();fileName.textContent=f.name;duration.textContent="--:--";empty.style.display="grid";setStatus("Video loaded. Use the video controls to play it.")});
video.addEventListener("loadedmetadata",()=>{duration.textContent=fmt(video.duration);empty.style.display="none";setStatus("Video ready.")});
video.addEventListener("error",()=>{empty.style.display="grid";setStatus("This video could not be played in the browser.")});
video.addEventListener("ended",()=>setStatus("Video ended. Tap the video display to replay."));
display.addEventListener("pointerup",e=>{if(video.ended&&e.target===video){video.currentTime=0;video.play().then(()=>setStatus("Video replaying.")).catch(()=>setStatus("Tap the video play control to start."))}});
$("update").addEventListener("click",()=>{setText(text.value.trim());if(text.value.trim())setStatus("Ticker text updated.");else setStatus("Ticker text cleared.")});
$("start").addEventListener("click",()=>{if(!text.value.trim())setStatus("Enter ticker text first.");running=true;anim.play();setStatus(text.value.trim()?"Ticker running.":"Ticker running; add text to display it.")});
$("stop").addEventListener("click",()=>{running=false;anim.pause();setStatus("Ticker stopped.")});
$("speed").addEventListener("input",e=>{anim.playbackRate=speeds[e.target.value];setStatus("Ticker speed changed.")});
document.querySelectorAll('input[name="pos"]').forEach(r=>r.addEventListener("change",()=>{setPos(r.value)}));
$("fullBtn").addEventListener("click",async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await display.requestFullscreen()}catch{setStatus("Full Screen is not available in this browser.")}});
